#!/bin/sh
#
# Copyright (c) 1997 Qualix Group, Inc. All Rights Reserved.
#
# $Id: start.m,v 1.7 1998/02/19 22:18:15 hle Exp $
#
#

#
# This shell script is run when the service group to which this
# service belongs has transited into SERVE state.
#
# Should return 0 if the service was start succesfully; otherwise,
# return non-zero
#

# The following environment variables are passed in:
# TOPDIR: HA+ installation directory. For example: /etc/opt/QUALha
# SGNAME: Service Group name. For example: 193.92.34.2
# SVCNAME: Service name. For example: httpd
topdir=${TOPDIR}
sgname=${SGNAME}
svcname=${SVCNAME}
 
# If TOPDIR or SGNAME or SVCNAME is not set, it is very likely that this
# script was run manually. Set svcdir to the current directory.
if test -z "${topdir}" -o -z "${sgname}" -o -z "${svcname}"
then
  svcdir="`pwd`"
else
  svcdir=${topdir}/sg/${sgname}/${svcname}.d
fi

cd ${svcdir}
bindir=${topdir}/bin

if test -f ./env
then
  . ./env
fi

# If the service is up and running, then there is no reason
# to try to start it.
#test=${svcdir}/test
#if test -f ${test}
#then
#  ${test}
#  if test "$?" -eq 0
#  then
#    echo "Service=${svcname} is already up and running."
#    exit 0
#  fi
#fi

if test X"${XXX_IN_QLOCK_NFSD}" = "X"
then
    argv0=$0
    argv=$*
    XXX_IN_QLOCK_NFSD=1
    export XXX_IN_QLOCK_NFSD
    if test -f ${bindir}/qlock
    then
      ${bindir}/qlock -d -p "$argv0 $argv" -l ${topdir}/etc/nfs.d.lock
    else
      $argv0 $argv
    fi
    status=$?

    exit ${status}
fi

echo "Starting service=${svcname}"

# lockd
${bindir}/pgrep "^${LOCKD}" > /dev/null 2>&1
status=$?
if test "${status}" -ne 0
then
echo "## Starting ${LOCKD} ..."
 ${LOCKD}
 status=$?
 if test "${status}" -ne 0
 then
   echo "## Cannot start ${LOCKD}."
   exit 1
 fi
else
 echo "## ${LOCKD} is running ..."
fi

# statd
qstatd=${bindir}/qstatd
${bindir}/pgrep "^${STATD}" > /dev/null 2>&1
status=$?
if test "${status}" -ne 0
then
 echo "## Starting ${STATD} ..."
 ${qstatd} -p ${STATD} -i ${sgname}
 status=$?
 if test "${status}" -ne 0
 then
   echo "## Cannot start ${STATD}."
   exit 1
 fi
else
 echo "## ${STATD} is running ..."
fi

# nfsd
if test "${UDP_PROTOCOL}" -eq 0
then
  protocol_options="-p tcp"
elif test "${TCP_PROTOCOL}" -eq 0
then
  protocol_options="-p udp"
else
  protocol_options="-a"
fi

nfsd_options="${protocol_options} ${NFSD_OPTIONS}"

${bindir}/pgrep "^${NFSD}"  > /dev/null 2>&1
status=$?
if test "${status}" -ne 0
then
 echo "## Starting ${NFSD} ..."
 ${NFSD} ${nfsd_options}
 status=$?
 if test "${status}" -ne 0
 then
   echo "## Cannot start ${NFSD}."
   exit 1
 fi
else
 echo "## ${NFSD} is running ..."
fi

# mountd
${bindir}/pgrep "^${MOUNTD}" > /dev/null 2>&1
status=$?
if test "${status}" -ne 0
then
 echo "## Starting ${MOUNTD} ..."
 ${MOUNTD}
 status=$?
 if test "${status}" -ne 0
 then
   echo "## Cannot start ${MOUNTD}."
   exit 1
 fi
else
 echo "## ${MOUNTD} is running ..."
fi

exit 0
