#!/bin/sh
#
# Copyright (c) 1996 Qualix Group, Inc. All Rights Reserved.
#
# $Id: failed.m,v 1.4 1998/09/04 00:29:05 ching Exp $
#
#

#
# This shell script will get run when a service has failed.
#
# Should return 0 if the service was start succesfully; otherwise,
# return non-zero
#

sendto="root"
mail="mailx"

# The following environment variables are passed in:
# TOPDIR: HA+ installation directory. For example: /etc/opt/QUALha
# SGNAME: Service Group name. For example: 193.92.34.2
# SVCNAME: Service name. For example: httpd
topdir=${TOPDIR}
sgname=${SGNAME}
svcname=${SVCNAME}
 
# If TOPDIR or SGNAME or SVCNAME is not set, very likely that this
# script was run manually. If so set svcdir to the current directory.
if test -z "${topdir}" -o -z "${sgname}" -o -z "${svcname}"
then
  svcdir="`pwd`"
else
  svcdir=${topdir}/sg/${sgname}/${svcname}.d
fi

cd ${svcdir}

# This is an example. User is encouraged to customize by adding additional
# commands to this file

echo "Service=${svcname} has failed."

(
  echo "On `date`, service=${svcname} in service group=${sgname} failed."
) | ${mail} -s "HA+ - ${sgname}:${svcname} failed" ${sendto}
