#!/bin/ksh

ResName=$1
shift
DS=$1

VCSHOME="${VCS_HOME:-/opt/VRTSvcs}"

. $VCSHOME/bin/ag_i18n_inc.sh
VCSAG_SET_ENVS $ResName

if [[ -x /usr/sbin/metastat ]]
then
	metastat=/usr/sbin/metastat
elif [[ -x /usr/opt/SUNWmd/sbin/metastat ]]
then
	metastat=/usr/opt/SUNWmd/sbin/metastat
else
	metastat=metastat
fi

if [[ -x /usr/sbin/metaset ]]
then
	metaset=/usr/sbin/metaset
elif [[ -x /usr/opt/SUNWmd/sbin/metaset ]]
then
	metaset=/usr/opt/SUNWmd/sbin/metaset
else
	metaset=metaset
fi

Out=$(${metastat} -s ${DS} 2>&1)
if (( $? == 0 ))
then
	exit 110
else
#	print "${Out}"
	exit 100
fi
